version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: myhomeapps-ombi_server_1
      APP_PORT: 3579
      PROXY_AUTH_WHITELIST: "/api/*"
      PROXY_AUTH_ADD: "false"
  server:
    image: ghcr.io/linuxserver/ombi:latest@sha256:0b512522e70d5418a393d60c3bc52dd01b519d95bf96528bfd53ee87a13c5312
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    privileged: true
    restart: on-failure
