version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: myhomeapps-sabnzbd_server_1
      APP_PORT: 8080
  server:
    image: lscr.io/linuxserver/sabnzbd:latest
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - /mnt/usb/Downloads:/downloads
    privileged: true
    restart: on-failure
