version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: myhomeapps-sabnzbd_server_1
      APP_PORT: 9797
  server:
    image: lscr.io/linuxserver/sabnzbd:latest
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - /mnt/usb/Downloads:/downloads
    ports:
      - 9797:8080
    privileged: true
    restart: on-failure
